/* Generated by scripts/generate_webex_viewer_types.js. Do not edit manually. */

export type WebexArgument = string | number | boolean | null | undefined;
export type WebexQuality = 'low' | 'medium' | 'high' | 'ultra';
export type WebexZoom = '+1' | '-1' | string;

export interface WebexRawEvent {
  readonly type: string;
  readonly d0: string;
  readonly d1: string;
  readonly d2: string;
}

export interface WebexRuntimeReadyEvent {
  readonly viewer: WebexViewer;
}

export interface WebexLoadStartEvent {
  readonly filename: string;
  readonly raw: WebexRawEvent;
}

export interface WebexLoadProgressEvent {
  readonly percentage: number;
  readonly raw: WebexRawEvent;
}

export interface WebexSceneReadyEvent { readonly raw: WebexRawEvent; }
export interface WebexErrorEvent { readonly error: WebexViewerError; readonly raw: WebexRawEvent; }

export interface WebexEventMap {
  event: WebexRawEvent;
  'runtime-ready': WebexRuntimeReadyEvent;
  'load-start': WebexLoadStartEvent;
  'load-progress': WebexLoadProgressEvent;
  'scene-ready': WebexSceneReadyEvent;
  error: WebexErrorEvent;
}

export interface WebexMountOptions {
  container?: string | Element;
  canvas?: string | HTMLCanvasElement;
  baseUrl?: string | URL;
  engine?: string | URL;
  apiKey?: string;
  scene?: string;
  background?: string;
  quality?: WebexQuality | string;
  autospin?: boolean;
  infotag?: boolean;
  shortcode?: string;
  loadTimeout?: number;
  contextAttributes?: WebGLContextAttributes;
  json?: Readonly<Record<string, unknown>>;
  onEvent?: (event: WebexRawEvent) => void;
}

export interface WebexCommandArguments {
  /** Protocol operation: api_key. */
  setApiKey: [arg0: WebexArgument];
  /** Protocol operation: apply_amb. */
  applyAmbienceLegacy: [arg0: WebexArgument];
  /** Protocol operation: apply_ambience. */
  applyAmbience: [arg0: WebexArgument];
  /** Protocol operation: apply_camera. */
  applyCamera: [arg0: WebexArgument];
  /** Protocol operation: apply_color. */
  applyColor: [arg0: WebexArgument];
  /** Protocol operation: apply_mannequin. */
  applyMannequin: [arg0: WebexArgument];
  /** Protocol operation: apply_material. */
  applyMaterialLegacy: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: apply_material_preset. */
  applyMaterialPreset: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: apply_material_to_object. */
  applyMaterialToObject: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: apply_mtl. */
  applyMaterial: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: auth_token. */
  setAuthToken: [arg0: WebexArgument];
  /** Protocol operation: cancel_sequence. */
  cancelSequence: [arg0: WebexArgument];
  /** Protocol operation: capture. */
  captureFrame: [];
  /** Protocol operation: close_scene. */
  closeScene: [];
  /** Protocol operation: create_link. */
  createLink: [];
  /** Protocol operation: delete_camera. */
  deleteCamera: [arg0: WebexArgument];
  /** Protocol operation: delete_color. */
  deleteColor: [arg0: WebexArgument];
  /** Protocol operation: delete_material_preset. */
  deleteMaterialPreset: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: draft_video. */
  draftVideo: [];
  /** Protocol operation: export_dressing. */
  exportDressing: [];
  /** Protocol operation: export_interactive. */
  exportInteractive: [];
  /** Protocol operation: get_actions. */
  getActions: [];
  /** Protocol operation: get_demo_models. */
  getDemoModels: [];
  /** Protocol operation: get_layer_attributes. */
  getLayerAttributes: [arg0: WebexArgument];
  /** Protocol operation: get_material_presets. */
  getMaterialPresets: [arg0: WebexArgument];
  /** Protocol operation: get_panels. */
  getPanels: [];
  /** Protocol operation: get_scene_objects. */
  getSceneObjects: [];
  /** Protocol operation: get_string. */
  getProperty: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: get_tonality_colors. */
  getTonalityColors: [arg0: WebexArgument];
  /** Protocol operation: import_dressing. */
  importDressing: [arg0: WebexArgument];
  /** Protocol operation: open_scene. */
  openScene: [arg0: WebexArgument];
  /** Protocol operation: panel. */
  selectPanel: [arg0: WebexArgument];
  /** Protocol operation: pick. */
  pick: [arg0: WebexArgument];
  /** Protocol operation: pick_engraving. */
  pickEngraving: [];
  /** Protocol operation: pick_focus. */
  pickFocus: [];
  /** Protocol operation: preview_video. */
  previewVideo: [];
  /** Protocol operation: probe_dressing. */
  probeDressing: [arg0: WebexArgument];
  /** Protocol operation: record_spinner. */
  recordSpinner: [];
  /** Protocol operation: record_video. */
  recordVideo: [];
  /** Protocol operation: save_camera. */
  saveCamera: [arg0: WebexArgument];
  /** Protocol operation: save_color. */
  saveColor: [arg0: WebexArgument];
  /** Protocol operation: save_material_preset. */
  saveMaterialPreset: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: save_scene. */
  saveScene: [];
  /** Protocol operation: set_autospin. */
  setAutospin: [arg0: WebexArgument];
  /** Protocol operation: set_clear_color. */
  setBackground: [arg0: WebexArgument];
  /** Protocol operation: set_infotag. */
  setInfotag: [arg0: WebexArgument];
  /** Protocol operation: set_layer_alias. */
  setLayerAlias: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: set_layer_family. */
  setLayerFamily: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: set_layer_tint. */
  setLayerTint: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: set_layer_visibility. */
  setLayerVisible: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: set_quality. */
  setQuality: [arg0: WebexArgument];
  /** Protocol operation: set_render_alpha_mode. */
  setRenderAlphaMode: [arg0: WebexArgument];
  /** Protocol operation: set_string. */
  setProperty: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: set_tonality. */
  setTonality: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: take_atlas. */
  takeAtlas: [];
  /** Protocol operation: take_picture. */
  takePicture: [];
  /** Protocol operation: take_picture_alpha. */
  takePictureAlpha: [];
  /** Protocol operation: video_next. */
  videoNext: [];
  /** Protocol operation: video_previous. */
  videoPrevious: [];
  /** Protocol operation: video_randomize. */
  videoRandomize: [];
  /** Protocol operation: viewer_mtl_choice_apply. */
  applyMaterialChoice: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_apply_defaults. */
  applyDefaultMaterialChoices: [arg0: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_create. */
  createMaterialChoice: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_delete. */
  deleteMaterialChoice: [arg0: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_label_set. */
  setMaterialChoiceLabel: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_member_set. */
  setMaterialChoiceMember: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_option_remove. */
  removeMaterialChoiceOption: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_option_set. */
  setMaterialChoiceOption: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_option_swap. */
  swapMaterialChoiceOptions: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_read. */
  readMaterialChoices: [];
  /** Protocol operation: viewer_mtl_choice_swap. */
  swapMaterialChoices: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_mtl_choice_thumbnail_set. */
  setMaterialChoiceThumbnail: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_obj_choice_apply. */
  applyObjectChoice: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_obj_choice_apply_defaults. */
  applyDefaultObjectChoices: [arg0: WebexArgument];
  /** Protocol operation: viewer_obj_choice_create. */
  createObjectChoice: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_obj_choice_delete. */
  deleteObjectChoice: [arg0: WebexArgument];
  /** Protocol operation: viewer_obj_choice_label_set. */
  setObjectChoiceLabel: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_obj_choice_member_set. */
  setObjectChoiceMember: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_obj_choice_option_label_set. */
  setObjectChoiceOptionLabel: [arg0: WebexArgument, arg1: WebexArgument, arg2: WebexArgument];
  /** Protocol operation: viewer_obj_choice_option_remove. */
  removeObjectChoiceOption: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: viewer_obj_choice_read. */
  readObjectChoices: [];
  /** Protocol operation: viewer_obj_choice_thumbnail_capture. */
  captureObjectChoiceThumbnail: [arg0: WebexArgument, arg1: WebexArgument];
  /** Protocol operation: webex_shortcode. */
  setShortcode: [arg0: WebexArgument];
  /** Protocol operation: zoom. */
  zoom: [arg0: WebexArgument];
}

export type WebexCommands = {
  readonly [Method in keyof WebexCommandArguments]:
    (...args: WebexCommandArguments[Method]) => void;
};

export type WebexCommandMethod = keyof WebexCommandArguments;
export type WebexProtocolCommand = 'api_key' | 'apply_amb' | 'apply_ambience' | 'apply_camera' | 'apply_color' | 'apply_mannequin' | 'apply_material' | 'apply_material_preset' | 'apply_material_to_object' | 'apply_mtl' | 'auth_token' | 'cancel_sequence' | 'capture' | 'close_scene' | 'create_link' | 'delete_camera' | 'delete_color' | 'delete_material_preset' | 'draft_video' | 'export_dressing' | 'export_interactive' | 'get_actions' | 'get_demo_models' | 'get_layer_attributes' | 'get_material_presets' | 'get_panels' | 'get_scene_objects' | 'get_string' | 'get_tonality_colors' | 'import_dressing' | 'open_scene' | 'panel' | 'pick' | 'pick_engraving' | 'pick_focus' | 'preview_video' | 'probe_dressing' | 'record_spinner' | 'record_video' | 'save_camera' | 'save_color' | 'save_material_preset' | 'save_scene' | 'set_autospin' | 'set_clear_color' | 'set_infotag' | 'set_layer_alias' | 'set_layer_family' | 'set_layer_tint' | 'set_layer_visibility' | 'set_quality' | 'set_render_alpha_mode' | 'set_string' | 'set_tonality' | 'take_atlas' | 'take_picture' | 'take_picture_alpha' | 'video_next' | 'video_previous' | 'video_randomize' | 'viewer_mtl_choice_apply' | 'viewer_mtl_choice_apply_defaults' | 'viewer_mtl_choice_create' | 'viewer_mtl_choice_delete' | 'viewer_mtl_choice_label_set' | 'viewer_mtl_choice_member_set' | 'viewer_mtl_choice_option_remove' | 'viewer_mtl_choice_option_set' | 'viewer_mtl_choice_option_swap' | 'viewer_mtl_choice_read' | 'viewer_mtl_choice_swap' | 'viewer_mtl_choice_thumbnail_set' | 'viewer_obj_choice_apply' | 'viewer_obj_choice_apply_defaults' | 'viewer_obj_choice_create' | 'viewer_obj_choice_delete' | 'viewer_obj_choice_label_set' | 'viewer_obj_choice_member_set' | 'viewer_obj_choice_option_label_set' | 'viewer_obj_choice_option_remove' | 'viewer_obj_choice_read' | 'viewer_obj_choice_thumbnail_capture' | 'webex_shortcode' | 'zoom';

export declare class WebexViewerError extends Error {
  readonly code: string;
  constructor(code: string, message: string, cause?: unknown);
}

export declare class WebexViewer {
  static current: WebexViewer | null;
  static readonly commands: Readonly<Record<WebexCommandMethod, readonly [WebexProtocolCommand, number]>>;
  static readonly Error: typeof WebexViewerError;
  readonly commands: WebexCommands;
  readonly canvas: HTMLCanvasElement;
  readonly disposed: boolean;
  static mount(options?: WebexMountOptions): Promise<WebexViewer>;
  send(operation: WebexProtocolCommand | (string & {}), args?: readonly WebexArgument[]): void;
  load(scene: string): Promise<this>;
  close(): void;
  setMaterial(object: WebexArgument, material: WebexArgument): void;
  setLayerVisible(layer: WebexArgument, visible: boolean): void;
  setProperty(scope: WebexArgument, property: WebexArgument, value: WebexArgument): void;
  getProperty(scope: WebexArgument, property: WebexArgument, timeout?: number): Promise<string>;
  setQuality(quality: WebexQuality | string): void;
  setBackground(color: string): void;
  setAutospin(enabled: boolean): void;
  zoom(direction: WebexZoom): void;
  capture(timeout?: number): Promise<string>;
  on<Event extends keyof WebexEventMap>(type: Event, listener: (event: WebexEventMap[Event]) => void): this;
  on(type: string, listener: (event: WebexRawEvent) => void): this;
  off<Event extends keyof WebexEventMap>(type: Event, listener: (event: WebexEventMap[Event]) => void): this;
  off(type: string, listener: (event: WebexRawEvent) => void): this;
  once<Event extends keyof WebexEventMap>(type: Event, listener: (event: WebexEventMap[Event]) => void): this;
  once(type: string, listener: (event: WebexRawEvent) => void): this;
  destroy(): void;
}

export declare const commands: typeof WebexViewer.commands;
export default WebexViewer;
